class ColorNames:

    WebColorMap = {}
    WebColorMap["Alice Blue"] = "#F0F8FF"
    WebColorMap["Antique White"] = "#FAEBD7"
    WebColorMap["Aqua"] = "#00FFFF"
    WebColorMap["Aquamarine"] = "#7FFFD4"
    WebColorMap["Azure"] = "#F0FFFF"
    WebColorMap["Beige"] = "#F5F5DC"
    WebColorMap["Bisque"] = "#FFE4C4"
    WebColorMap["Black"] = "#000000"
    WebColorMap["Blanched Almond"] = "#FFEBCD"
    WebColorMap["Blue"] = "#0000FF"
    WebColorMap["Blue Violet"] = "#8A2BE2"
    WebColorMap["Brown"] = "#A52A2A"
    WebColorMap["Burly Wood"] = "#DEB887"
    WebColorMap["Cadet Blue"] = "#5F9EA0"
    WebColorMap["Chartreuse"] = "#7FFF00"
    WebColorMap["Chocolate"] = "#D2691E"
    WebColorMap["Coral"] = "#FF7F50"
    WebColorMap["Cornflower Blue"] = "#6495ED"
    WebColorMap["Cornsilk"] = "#FFF8DC"
    WebColorMap["Crimson"] = "#DC143C"
    WebColorMap["Cyan"] = "#00FFFF"
    WebColorMap["Dark Blue"] = "#00008B"
    WebColorMap["Dark Cyan"] = "#008B8B"
    WebColorMap["Dark Golden Rod"] = "#B8860B"
    WebColorMap["Dark Gray"] = "#A9A9A9"
    WebColorMap["Dark Grey"] = "#A9A9A9"
    WebColorMap["Dark Green"] = "#006400"
    WebColorMap["Dark Khaki"] = "#BDB76B"
    WebColorMap["Dark Magenta"] = "#8B008B"
    WebColorMap["Dark Olive Green"] = "#556B2F"
    WebColorMap["Dark Orange"] = "#FF8C00"
    WebColorMap["Dark Orchid"] = "#9932CC"
    WebColorMap["Dark Red"] = "#8B0000"
    WebColorMap["Dark Salmon"] = "#E9967A"
    WebColorMap["Dark Sea Green"] = "#8FBC8F"
    WebColorMap["Dark Slate Blue"] = "#483D8B"
    WebColorMap["Dark Slate Gray"] = "#2F4F4F"
    WebColorMap["Dark Slate Grey"] = "#2F4F4F"
    WebColorMap["Dark Turquoise"] = "#00CED1"
    WebColorMap["Dark Violet"] = "#9400D3"
    WebColorMap["Deep Pink"] = "#FF1493"
    WebColorMap["Deep Sky Blue"] = "#00BFFF"
    WebColorMap["Dim Gray"] = "#696969"
    WebColorMap["Dodger Blue"] = "#1E90FF"
    WebColorMap["Fire Brick"] = "#B22222"
    WebColorMap["Floral White"] = "#FFFAF0"
    WebColorMap["Forest Green"] = "#228B22"
    WebColorMap["Fuchsia"] = "#FF00FF"
    WebColorMap["Gainsboro"] = "#DCDCDC"
    WebColorMap["Ghost White"] = "#F8F8FF"
    WebColorMap["Gold"] = "#FFD700"
    WebColorMap["Golden Rod"] = "#DAA520"
    WebColorMap["Gray"] = "#808080"
    WebColorMap["Grey"] = "#808080"
    WebColorMap["Green"] = "#008000"
    WebColorMap["Green Yellow"] = "#ADFF2F"
    WebColorMap["Honey Dew"] = "#F0FFF0"
    WebColorMap["Hot Pink"] = "#FF69B4"
    WebColorMap["Indian Red"] = "#CD5C5C"
    WebColorMap["Indigo"] = "#4B0082"
    WebColorMap["Ivory"] = "#FFFFF0"
    WebColorMap["Khaki"] = "#F0E68C"
    WebColorMap["Lavender"] = "#E6E6FA"
    WebColorMap["Lavender Blush"] = "#FFF0F5"
    WebColorMap["Lawn Green"] = "#7CFC00"
    WebColorMap["Lemon Chiffon"] = "#FFFACD"
    WebColorMap["Light Blue"] = "#ADD8E6"
    WebColorMap["Light Coral"] = "#F08080"
    WebColorMap["Light Cyan"] = "#E0FFFF"
    WebColorMap["Light GoldenRodYellow"] = "#FAFAD2"
    WebColorMap["Light Gray"] = "#D3D3D3"
    WebColorMap["Light Grey"] = "#D3D3D3"
    WebColorMap["Light Green"] = "#90EE90"
    WebColorMap["Light Pink"] = "#FFB6C1"
    WebColorMap["Light Salmon"] = "#FFA07A"
    WebColorMap["Light Sea Green"] = "#20B2AA"
    WebColorMap["Light Sky Blue"] = "#87CEFA"
    WebColorMap["Light Slate Gray"] = "#778899"
    WebColorMap["Light Slate Grey"] = "#778899"
    WebColorMap["Light Steel Blue"] = "#B0C4DE"
    WebColorMap["Light Yellow"] = "#FFFFE0"
    WebColorMap["Lime"] = "#00FF00"
    WebColorMap["Lime Green"] = "#32CD32"
    WebColorMap["Linen"] = "#FAF0E6"
    WebColorMap["Magenta"] = "#FF00FF"
    WebColorMap["Maroon"] = "#800000"
    WebColorMap["Medium Aqua Marine"] = "#66CDAA"
    WebColorMap["Medium Blue"] = "#0000CD"
    WebColorMap["Medium Orchid"] = "#BA55D3"
    WebColorMap["Medium Purple"] = "#9370D8"
    WebColorMap["Medium Sea Green"] = "#3CB371"
    WebColorMap["Medium Slate Blue"] = "#7B68EE"
    WebColorMap["Medium Spring Green"] = "#00FA9A"
    WebColorMap["Medium Turquoise"] = "#48D1CC"
    WebColorMap["Medium VioletRed"] = "#C71585"
    WebColorMap["Midnight Blue"] = "#191970"
    WebColorMap["Mint Cream"] = "#F5FFFA"
    WebColorMap["Misty Rose"] = "#FFE4E1"
    WebColorMap["Moccasin"] = "#FFE4B5"
    WebColorMap["Navajo White"] = "#FFDEAD"
    WebColorMap["Navy"] = "#000080"
    WebColorMap["Old Lace"] = "#FDF5E6"
    WebColorMap["Olive"] = "#808000"
    WebColorMap["Olive Drab"] = "#6B8E23"
    WebColorMap["Orange"] = "#FFA500"
    WebColorMap["Orange Red"] = "#FF4500"
    WebColorMap["Orchid"] = "#DA70D6"
    WebColorMap["Pale Golden Rod"] = "#EEE8AA"
    WebColorMap["Pale Green"] = "#98FB98"
    WebColorMap["Pale Turquoise"] = "#AFEEEE"
    WebColorMap["Pale Violet Red"] = "#D87093"
    WebColorMap["Papaya Whip"] = "#FFEFD5"
    WebColorMap["Peach Puff"] = "#FFDAB9"
    WebColorMap["Peru"] = "#CD853F"
    WebColorMap["Pink"] = "#FFC0CB"
    WebColorMap["Plum"] = "#DDA0DD"
    WebColorMap["Powder Blue"] = "#B0E0E6"
    WebColorMap["Purple"] = "#800080"
    WebColorMap["Red"] = "#FF0000"
    WebColorMap["Rosy Brown"] = "#BC8F8F"
    WebColorMap["Royal Blue"] = "#4169E1"
    WebColorMap["Saddle Brown"] = "#8B4513"
    WebColorMap["Salmon"] = "#FA8072"
    WebColorMap["Sandy Brown"] = "#F4A460"
    WebColorMap["Sea Green"] = "#2E8B57"
    WebColorMap["Sea Shell"] = "#FFF5EE"
    WebColorMap["Sienna"] = "#A0522D"
    WebColorMap["Silver"] = "#C0C0C0"
    WebColorMap["Sky Blue"] = "#87CEEB"
    WebColorMap["Slate Blue"] = "#6A5ACD"
    WebColorMap["Slate Gray"] = "#708090"
    WebColorMap["Slate Grey"] = "#708090"
    WebColorMap["Snow"] = "#FFFAFA"
    WebColorMap["Spring Green"] = "#00FF7F"
    WebColorMap["Steel Blue"] = "#4682B4"
    WebColorMap["Tan"] = "#D2B48C"
    WebColorMap["Teal"] = "#008080"
    WebColorMap["Thistle"] = "#D8BFD8"
    WebColorMap["Tomato"] = "#FF6347"
    WebColorMap["Turquoise"] = "#40E0D0"
    WebColorMap["Violet"] = "#EE82EE"
    WebColorMap["Wheat"] = "#F5DEB3"
    WebColorMap["White"] = "#FFFFFF"
    WebColorMap["White Smoke"] = "#F5F5F5"
    WebColorMap["Yellow"] = "#FFFF00"
    WebColorMap["Yellow Green"] = "#9ACD32"
    
    @staticmethod
    def rgbFromStr(s):  
        # s starts with a #.  
        r, g, b = int(s[1:3],16), int(s[3:5], 16),int(s[5:7], 16)  
        return r, g, b  
    
    @staticmethod
    def color_name(s):
        r, g, b = int(s[1:3],16), int(s[3:5], 16),int(s[5:7], 16)  
        return ColorNames.findNearestWebColorName(r, g, b) 
    
    @staticmethod
    def findNearestWebColorName(R,G,B):  
        return ColorNames.findNearestColorName(R,G,B,ColorNames.WebColorMap)
    
    @staticmethod
    def findNearestColorName(R,G,B,Map):  
        mindiff = None
        for d in Map:  
            r, g, b = ColorNames.rgbFromStr(Map[d])  
            diff = abs(R -r)*256 + abs(G-g)* 256 + abs(B- b)* 256   
            if mindiff is None or diff < mindiff:  
                mindiff = diff  
                mincolorname = d  
        return mincolorname             
  

